apiVersion: v1
kind: Service
metadata:
  name: designsystem-db
spec:
  selector:
    app: designsystem-db
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: designsystem-db-deployment
  labels:
    app: designsystem-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: designsystem-db
  template:
    metadata:
      labels:
        app: designsystem-db
    spec:
      containers:
        - name: designsystem-db
          image: postgres:alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: designsystem
            - name: POSTGRES_PASSWORD
              value: designsystem
            - name: POSTGRES_USER
              value: designsystem
