apiVersion: v1
kind: Service
metadata:
  name: designsystem-frontend-service
spec:
  selector:
    app: designsystem-frontend
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: designsystem-frontend-deployment
  labels:
    app: designsystem-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: designsystem-frontend
  template:
    metadata:
      labels:
        app: designsystem-frontend
    spec:
      containers:
        - name: designsystem-frontend
          image: mrako/designsystem-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ENDPOINT
              value: https://designsystem.hopefully.works/api
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: designsystem-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: designsystem.hopefully.works
    http:
      paths:
      - path: /
        backend:
          serviceName: designsystem-frontend-service
          servicePort: 80
