version: '2'

services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    environment:
      ENDPOINT: https://designsystem.hopefully.works/api

volumes:
  dbdata:
