version: '2'

services:
  robot.frontend:
    build: frontend
    ports:
      - 8000

  robot:
    build: robot
    command: sh -c '/robot/wait-for robot.frontend:8000 -t 5 -r 10 --wget -- python /robot/run.py --outputdir /results'
    environment:
      BROWSER: HeadlessChrome
      SERVER: http://robot.frontend:8000
    volumes:
      - ./robot:/robot:ro
      - ./results/robot:/results:rw
    depends_on:
      - robot.frontend
